/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список предстоящих встреч (все типы событий)
         * @description Страница предстоящих встреч.
         *
         *     Возвращает бронирования всех типов событий в одном списке,
         *     отсортированные по времени начала.
         */
        get: operations["Admin_listBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bookings/{bookingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить бронирование по id
         * @description Детали конкретного бронирования.
         */
        get: operations["Admin_getBooking"];
        put?: never;
        post?: never;
        /**
         * Отменить бронирование
         * @description Отмена бронирования владельцем.
         */
        delete: operations["Admin_cancelBooking"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список типов событий */
        get: operations["EventTypes_list"];
        put?: never;
        /** Создать тип события */
        post: operations["EventTypes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/event-types/{eventTypeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить тип события по id */
        get: operations["EventTypes_read"];
        /** Обновить тип события */
        put: operations["EventTypes_update"];
        post?: never;
        /** Удалить тип события */
        delete: operations["EventTypes_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить профиль владельца
         * @description Профиль владельца календаря (только чтение).
         */
        get: operations["Admin_getOwner"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Создать бронирование на выбранный слот
         * @description Создание бронирования на выбранный слот.
         *
         *     Ошибки:
         *     - 404 — указанный тип события не существует;
         *     - 409 — выбранное время уже занято другим бронированием
         *     (в т.ч. другого типа события) или слот вне окна 14 дней;
         *     - 422 — некорректные данные гостя или формат запроса.
         */
        post: operations["Public_createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список видов брони
         * @description Страница с видами брони.
         *     Для каждого вида доступны название, описание и длительность.
         */
        get: operations["EventTypes_list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/event-types/{eventTypeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить вид брони по id */
        get: operations["EventTypes_read_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/event-types/{eventTypeId}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Свободные слоты типа события на ближайшие 14 дней
         * @description Календарь свободных слотов выбранного типа события.
         *
         *     Слоты формируются на 14 дней начиная с текущей даты. Слот, на время
         *     которого уже есть бронирование (любого типа события), в список не попадает.
         */
        get: operations["EventTypes_listSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Описание ошибки. */
        ApiError: {
            /** @description Машиночитаемый код ошибки. */
            code: string;
            /** @description Человекочитаемое сообщение. */
            message: string;
        };
        /** @description Бронирование слота гостем. */
        Booking: {
            /** @description Идентификатор бронирования. */
            readonly id: string;
            /** @description Идентификатор типа события, на который сделана запись. */
            eventTypeId: string;
            /**
             * Format: date-time
             * @description Начало встречи (UTC, ISO 8601).
             */
            start: string;
            /**
             * Format: date-time
             * @description Конец встречи (UTC, ISO 8601).
             */
            readonly end: string;
            /** @description Имя гостя. */
            guestName: string;
            /** @description Email гостя. */
            guestEmail: string;
            /** @description Необязательный комментарий гостя к встрече. */
            notes?: string;
            /** @description Статус бронирования. */
            readonly status: components["schemas"]["BookingStatus"];
            /**
             * Format: date-time
             * @description Момент создания бронирования (UTC, ISO 8601).
             */
            readonly createdAt: string;
        };
        /** @description Данные для создания бронирования гостем. */
        BookingCreate: {
            /** @description Идентификатор типа события. */
            eventTypeId: string;
            /**
             * Format: date-time
             * @description Начало выбранного слота (UTC, ISO 8601).
             */
            start: string;
            /** @description Имя гостя. */
            guestName: string;
            /** @description Email гостя. */
            guestEmail: string;
            /** @description Необязательный комментарий гостя. */
            notes?: string;
        };
        /**
         * @description Статус бронирования.
         * @enum {string}
         */
        BookingStatus: "confirmed" | "cancelled";
        /** @description Тип события, на который можно записаться. */
        EventType: {
            /** @description Идентификатор типа события. */
            readonly id: string;
            /** @description Название типа события, например "Демо продукта". */
            title: string;
            /** @description Описание типа события для гостя. */
            description: string;
            /**
             * Format: int32
             * @description Длительность встречи в минутах.
             */
            durationMinutes: number;
        };
        /** @description Данные для создания типа события. */
        EventTypeCreate: {
            /** @description Название типа события. */
            title: string;
            /** @description Описание типа события. */
            description: string;
            /**
             * Format: int32
             * @description Длительность встречи в минутах.
             */
            durationMinutes: number;
        };
        /** @description Запрашиваемый ресурс не найден. */
        NotFoundError: {
            /** @enum {string} */
            code: "not_found";
            message: string;
        };
        /** @description Владелец календаря — единственный предзаданный профиль. */
        Owner: {
            /** @description Идентификатор владельца. */
            readonly id: string;
            /** @description Отображаемое имя владельца. */
            name: string;
            /** @description Контактный email владельца. */
            email: string;
            /** @description Таймзона владельца в формате IANA, например "Europe/Moscow". */
            timeZone: string;
        };
        /** @description Свободный слот для записи на конкретный тип события. */
        Slot: {
            /**
             * Format: date-time
             * @description Начало слота (UTC, ISO 8601).
             */
            start: string;
            /**
             * Format: date-time
             * @description Конец слота (UTC, ISO 8601). Равен start + durationMinutes типа события.
             */
            end: string;
        };
        /** @description Свободные слоты типа события в окне записи. */
        SlotList: {
            /** @description Идентификатор типа события. */
            eventTypeId: string;
            /**
             * Format: date-time
             * @description Начало окна доступности (UTC, ISO 8601).
             */
            windowStart: string;
            /**
             * Format: date-time
             * @description Конец окна доступности (UTC, ISO 8601). По умолчанию windowStart + 14 дней.
             */
            windowEnd: string;
            /** @description Список свободных слотов внутри окна. */
            slots: components["schemas"]["Slot"][];
        };
        /** @description Время уже занято другим бронированием. */
        SlotTakenError: {
            /** @enum {string} */
            code: "slot_taken";
            message: string;
        };
        /** @description Некорректные входные данные. */
        ValidationError: {
            /** @enum {string} */
            code: "validation_failed";
            message: string;
            /** @description Список полей с ошибками. */
            fields?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Admin_listBookings: {
        parameters: {
            query?: {
                /** @description Показывать встречи начиная с этого момента. По умолчанию — текущее время. */
                from?: string;
                /** @description Показывать встречи до этого момента. */
                to?: string;
                /** @description Фильтр по статусу. По умолчанию возвращаются только confirmed. */
                status?: components["schemas"]["BookingStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
        };
    };
    Admin_getBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description Запрашиваемый ресурс не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    Admin_cancelBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description Запрашиваемый ресурс не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    EventTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    EventTypes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description Некорректные входные данные. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    EventTypes_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description Запрашиваемый ресурс не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    EventTypes_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description Запрашиваемый ресурс не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description Некорректные входные данные. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    EventTypes_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Запрашиваемый ресурс не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    Admin_getOwner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Owner"];
                };
            };
        };
    };
    Public_createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description Запрашиваемый ресурс не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description Время уже занято другим бронированием. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotTakenError"];
                };
            };
            /** @description Некорректные входные данные. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    EventTypes_list_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    EventTypes_read_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description Запрашиваемый ресурс не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    EventTypes_listSlots: {
        parameters: {
            query?: {
                /** @description Начало окна. По умолчанию — текущая дата. Не может быть в прошлом. */
                from?: string;
            };
            header?: never;
            path: {
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotList"];
                };
            };
            /** @description Запрашиваемый ресурс не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
}
